services:
  catalog:
    image: projectnessie/nessie
    container_name: catalog
    networks:
      general-network:
    ports:
      - 19120:19120

  trino:
    image: trinodb/trino
    container_name: trino
    networks:
      general-network:
    ports:
      - 8085:8080
    volumes:
      - "./iceberg.properties:/etc/trino/catalog/iceberg.properties"
      - "./post-init.sh:/tmp/post-init.sh"
      - "./post-init.sql:/tmp/post-init.sql"
    command:
      - "/tmp/post-init.sh"


  storage:
    image: minio/minio
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      general-network:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  # Minio Client Container
  mc:
    depends_on:
      - storage
    image: minio/mc
    container_name: mc
    networks:
      general-network:
        aliases:
          - minio.storage
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://storage:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/repositories;
      /usr/bin/mc mb minio/iceberg;
      /usr/bin/mc anonymous set download minio/repositories;
      /usr/bin/mc anonymous set download minio/iceberg;
      tail -f /dev/null
      "
networks:
  general-network:
    external: true